UI improvement
openlattice/chronicle pull request #75
Opened 2020-12-04 21:51 UTC by anzioka

PR:

Use material components + OL color palette

<img width="392" alt="Screen Shot 2020-12-04 at 12 52 23 PM" src="https://user-images.githubusercontent.com/15723547/101218260-9d97bb00-3637-11eb-8eee-bc50eefc7e19.png">
<img width="386" alt="Screen Shot 2020-12-04 at 12 40 44 PM" src="https://user-images.githubusercontent.com/15723547/101218264-9e305180-3637-11eb-98f1-abfff5acd43c.png">
<img width="426" alt="Screen Shot 2020-12-04 at 10 39 12 AM" src="https://user-images.githubusercontent.com/15723547/101218268-9ec8e800-3637-11eb-8987-1aa645e877ad.png">
<img width="460" alt="Screen Shot 2020-12-04 at 10 10 36 AM" src="https://user-images.githubusercontent.com/15723547/101218270-9f617e80-3637-11eb-8f07-96288e5169b4.png">
<img width="432" alt="Screen Shot 2020-12-04 at 9 44 57 AM" src="https://user-images.githubusercontent.com/15723547/101218271-9f617e80-3637-11eb-8319-abd0377d8679.png">

2020-12-09 06:10 UTC, solomontang commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
does the DayNight mean it will follow system preferences for dark mode? if so that's pretty sick

2020-12-09 06:11 UTC, solomontang approved these changes

2020-12-12 00:50 UTC, UnsungHero97 requested changes

2020-12-12 00:50 UTC, UnsungHero97 commented on app/src/main/res/values/colors.xml
>      <color name="neutral">#555e6f</color>
Please use the LUK colors. Some of these are from the old / legacy colors, and others are not defined in LUK.

2020-12-12 01:27 UTC, merged

2020-12-12 03:24 UTC, UnsungHero97 approved these changes